import os
import glob
from PIL import Image, ImageChops, ImageDraw

downloads_folder = r'C:\Users\2005n\Downloads\loghi'
target_folder = 'public/assets/logos'

file_map = {
    'Gemini_Generated_Image_1465j11465j11465.png': 'agip.png',
    'Gemini_Generated_Image_224swy224swy224s.png': 'conad.png',
    'Gemini_Generated_Image_3fyksd3fyksd3fyk.png': 'coop.png',
    'Gemini_Generated_Image_4alp994alp994alp.png': 'ip.png',
    'Gemini_Generated_Image_6t8ch86t8ch86t8c.png': 'shell.png',
    'Gemini_Generated_Image_8vycuk8vycuk8vyc.png': 'esso.png',
    'Gemini_Generated_Image_tqckf2tqckf2tqck.png': 'repsol.png',
    'Gemini_Generated_Image_xf00z3xf00z3xf00.png': 'q8.png',
    'Gemini_Generated_Image_z0abuaz0abuaz0ab.png': 'tamoil.png',
}

for source_file, dest_name in file_map.items():
    source_path = os.path.join(downloads_folder, source_file)
    dest_path = os.path.join(target_folder, dest_name)
    
    if not os.path.exists(source_path):
        print(f"Source not found: {source_path}")
        continue
        
    try:
        img = Image.open(source_path).convert('RGB')
        
        # Create a copy to find the bounding box
        mask_img = img.copy()
        draw = ImageDraw.Draw(mask_img)
        
        w, h = mask_img.size
        # Draw a black rectangle over the bottom right corner to hide the watermark
        # The Gemini watermark is usually at the bottom right. We'll mask out the bottom 20% right 20%
        draw.rectangle([int(w * 0.75), int(h * 0.75), w, h], fill=(0, 0, 0))
        
        # Convert to grayscale to evaluate brightness
        gray = mask_img.convert("L")
        
        # High threshold to only keep the bright white logo parts
        mask = gray.point(lambda p: 255 if p > 80 else 0)
        
        bbox = mask.getbbox()
        
        if bbox:
            # Crop the ORIGINAL image (but the watermark is still there if it falls within the bbox!)
            # Actually, we don't want the watermark at all. So we crop from mask_img which has the watermark blacked out.
            cropped = mask_img.crop(bbox)
            
            cw, ch = cropped.size
            size = max(cw, ch)
            
            # Pad by 1.25 to make them look perfectly sized inside the circle
            padded_size = int(size * 1.25)
            
            new_img = Image.new('RGB', (padded_size, padded_size), (0, 0, 0))
            offset = ((padded_size - cw) // 2, (padded_size - ch) // 2)
            new_img.paste(cropped, offset)
            
            new_img.save(dest_path)
            
            # Copy agip to eni
            if dest_name == 'agip.png':
                new_img.save(os.path.join(target_folder, 'eni.png'))
                
            print(f"Cropped and squared {dest_name}")
        else:
            print(f"Skipped {dest_name} (no bright pixels found)")
    except Exception as e:
        print(f"Error processing {source_path}: {e}")

# Now handle generic.png if we need to? The generic one was generated by me, might not have a watermark.
